export enum ProductCategory {
  PANES_TRADICIONALES = 'PANES_TRADICIONALES',
  MASA_MADRE_ARTESANAL = 'MASA_MADRE_ARTESANAL',
  PASTELERIA_REPOSTERIA = 'PASTELERIA_REPOSTERIA',
  LINEA_SALUDABLE_ANDINA = 'LINEA_SALUDABLE_ANDINA',
  EMPANADAS_MASAS_CALIENTES = 'EMPANADAS_MASAS_CALIENTES',
  COMBOS_CANASTAS = 'COMBOS_CANASTAS',
  BEBIDAS_TRADICIONALES = 'BEBIDAS_TRADICIONALES',
}

export enum BakingShift {
  MADRUGADA = 'MADRUGADA', // 04:30 - 07:00 AM (Pan de la mañana caliente)
  TARDE = 'TARDE',         // 15:30 - 18:30 PM (Lonche caliente)
  NOCTURNO = 'NOCTURNO',   // Masas fermentadas lentas y pastelería
}
